---
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#organizing-host-and-group-variables

############################
# role:prepare
############################
# 节点基础环境准备完成后是否自动重启系统
REBOOT: "no"

# 本地 ntp 服务器地址
NTP_HOST: "ntp.local"

############################
# role:runtime [docker, containerd]
############################
# 本地镜像仓库配置
REGISTRY_VER: "2.8.1"
REGISTRY_HOST: "registry.local"
REGISTRY_PORT: "5000"
REGISTRY_SERVICE: "{{ REGISTRY_HOST }}:{{ REGISTRY_PORT }}"

# 镜像仓库加速地址
REGISTRY_MIRRORS:
  docker.io:
    - "https://mirror.baidubce.com"
    - "https://hub-mirror.c.163.com"
    - "https://docker.mirrors.ustc.edu.cn"
  gcr.io:
    - "https://gcr.mirrors.ustc.edu.cn"
  k8s.gcr.io:
    - "https://gcr.mirrors.ustc.edu.cn/google-containers"
  quay.io:
    - "https://quay.mirrors.ustc.edu.cn"

# [docker]
DOCKER_VER: "20.10.17"
# [docker] 信任的 HTTP 仓库
DOCKER_INSECURE_REGISTRIES:
  - "{{ REGISTRY_SERVICE }}"

# [containerd]
CONTAINERD_VER: "1.6.8"
# [containerd] 信任的 HTTP 仓库
CONTAINERD_INSECURE_REGISTRIES:
  - "http://{{ REGISTRY_SERVICE }}"
# [containerd] pod 根容器镜像版本
CONTAINERD_PAUSE_VER: "3.7"

############################
# role:kube-master [1.23.*, 1.24.*, 1.25.*]
############################
# kubernetes 版本
K8S_VER: "1.25.2"
# kubernetes 组件镜像加速地址
K8S_IMAGE_REPOSITORY: "registry.aliyuncs.com/google_containers"

# 高可用模式依赖 haproxy, keepalived
# [haproxy]
HAPROXY_VER: "2.1.4"
# [keepalived]
KEEPALIVED_VER: "2.0.17"

############################
# role:kube-worker
############################
# 配置为 kube 组件（kubelet,kube-proxy,dockerd等）预留的资源量
# 数值设置详见 templates/kubeadm-config.yaml.j2
KUBE_RESERVED_ENABLE: "no"
# k8s 官方不建议草率开启 system-reserved, 除非你基于长期监控，了解系统的资源占用状况；
# 并且随着系统运行时间，需要适当增加资源预留，数值设置详见 templates/kubeadm-config.yaml.j2
# 系统预留设置基于 4c/8g 虚机，最小化安装系统服务，如果使用高性能物理机可以适当增加预留
# 另外，集群安装时候 apiserver 等资源占用会短时较大，建议至少预留 1g 内存
SYS_RESERVED_ENABLE: "no"

############################
# role:network [calico, flannel]
############################
# [calico]
CALICO_VER: "3.24.1"

# [flannel]
FLANNEL_VER: "0.19.2"
FLANNEL_CNI_PLUGIN_VER: "1.1.0"

############################
# role:cluster-addon [helm, nodelocaldns, metrics-server, nfs-provisioner, prometheus, dashboard]
############################
# [helm]
# 是否启用 helm 扩展
HELM_ENABLE: "no"
HELM_VER: "3.9.4"

# [nodelocaldns]
# 是否启用 nodelocaldns 扩展
NODELOCALDNS_ENABLE: "no"
NODELOCALDNS_VER: "1.22.8"
# 设置 node local dns 地址
LOCAL_DNS_SERVER: "169.254.20.10"

# [metrics-server]
# 是否启用 metrics-server 扩展
METRICES_SERVER_ENABLE: "no"
METRICES_SERVER_VER: "0.6.1"

# [nfs-provisioner]
# 是否启用 nfs-provisioner 扩展
NFS_PROVISIONER_ENABLE: "no"
NFS_PROVISIONER_VER: "4.0.2"
NFS_PROVISIONER_NAMESPACE: "nfs-provisioner"
NFS_STORAGE_CLASS: "nfs-storage"

# [prometheus]
# 是否启用 prometheus 扩展（若启用该扩展需要同时启用 helm 扩展）
PROMETHEUS_ENABLE: "no"
PROMETHEUS_VER: "35.5.1"
PROMETHEUS_NAMESPACE: "monitoring"

# [dashboard]
# 是否启用 dashboard 扩展
DASHBOARD_ENABLE: "yes"
DASHBOARD_VER: "2.6.1"
METRICS_SCRAPER_VER: "1.0.8"
