---
- set_fact:
    chronyd_running: >-
      {{
        ("chronyd.service" in ansible_facts.services) and
        (ansible_facts.services["chronyd.service"]["state"] == "running")
      }}

- name: stop chronyd service
  systemd:
    name: chronyd
    state: stopped
    enabled: no
  when: chronyd_running

- name: remove chrony.d directory
  file:
    path: /etc/chrony.d
    state: absent

- name: uninstall packages
  yum:
    name:
      - kubeadm
      - kubectl
      - kubelet
      - docker-compose-plugin
      - docker-ce
      - containerd.io
      - chrony
    state: absent

- name: remove ~/.bashrc related settings
  blockinfile:
    path: ~/.bashrc
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_items:
    - crictl
    - kubectl

- name: remove /etc/profile related settings
  blockinfile:
    path: /etc/profile
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_items:
    - docker-compose

- name: remove kubernetes related files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/cni
    - /etc/containerd
    - /etc/crictl.yaml
    - /etc/docker
    - /etc/flannel
    - /etc/kubernetes
    - /etc/modules-load.d/10-k8s-modules.conf
    - /etc/sysctl.d/95-k8s-sysctl.conf
    - /etc/systemd/system.conf.d/30-k8s-ulimits.conf
    - /etc/systemd/system/containerd.service
    - /etc/systemd/system/containerd.service.d
    - /etc/systemd/system/docker.service
    - /etc/systemd/system/docker.service.d
    - /etc/systemd/system/docker.service.requires/
    - /etc/systemd/system/kubelet.service.d
    - /etc/systemd/system/kubernetes.slice
    - /opt/cni
    - /opt/containerd
    - /opt/data
    # - /run/calico
    - /run/flannel
    - /run/containerd
    - /run/docker
    - /run/docker.sock
    - /run/dockershim.sock
    - /usr/bin/docker
    - /usr/share/bash-completion/completions/docker
    - /var/lib/calico
    - /var/lib/cni
    - /var/lib/containerd
    - /var/lib/docker
    - /var/lib/dockershim
    - /var/lib/kubelet
    - /var/log/calico
    - /var/log/containers
    - /var/log/pods
    # - /var/run/calico
    - /var/run/docker
    - /var/run/docker.sock
    - /var/run/containerd
    - /var/run/dockershim.sock

- name: just force systemd to re-execute itself
  systemd:
    daemon_reexec: yes

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: restart network
  systemd:
    name: NetworkManager
    state: restarted
