---
- set_fact:
    kubelet_running: |-
      {{
        ("kubelet.service" in ansible_facts.services) and
        (ansible_facts.services["kubelet.service"]["state"] == "running")
      }}

- name: "reset node: {{ inventory_hostname }}"
  command: kubeadm reset -f
  ignore_errors: true
  when: kubelet_running

- name: stop kubelet service
  service:
    name: kubelet
    state: stopped
    enabled: no
  when: kubelet_running
