---
- name: populate service facts
  service_facts:

- include_tasks: kubelet.yml

- include_tasks: runtime.yml

- include_tasks: network.yml

- include_tasks: centos.yml
  when: ansible_distribution in ['CentOS', 'Rocky']
