---
tmp_download_directory: /tmp/download

k8s_helm_enable: true
k8s_helm_version: 3.9.4

k8s_ha_enable: false
k8s_ha_version: 2.1.4

k8s_external_etcd: false
k8s_image_repository: "registry.aliyuncs.com/google_containers"
k8s_service_cidr: "10.96.0.0/12"
k8s_pod_cidr: "10.244.0.0/16"
k8s_nodeport_ipranges: []

k8s_apiserver_interface: ens18
k8s_apiserver_port: 6443
k8s_apiserver_advertise_address: "{{ hostvars[inventory_hostname]['ansible_' + k8s_apiserver_interface].ipv4.address }}"

k8s_apiserver_vinterface: "{{ k8s_apiserver_interface }}"
k8s_apiserver_vport: 5000
k8s_apiserver_vip: 192.168.0.1
k8s_apiserver_vmask: 24

k8s_keepalived_version: 2.0.17
k8s_keepalived_state: BACKUP
k8s_keepalived_priority: 100
k8s_keepalived_priority_base: 125
k8s_keepalived_priority_delta: 5
k8s_keepalived_interface: "{{ k8s_apiserver_vinterface }}"
k8s_keepalived_virtual_router_id: 100
k8s_keepalived_auth_pass: BSiAcmJh0mio5Ugc0Z
k8s_keepalived_virtual_ipaddress: "{{ k8s_apiserver_vip }}/{{ k8s_apiserver_vmask }} dev {{ k8s_apiserver_vinterface }}"
