---
- name: get all partition info
  command: "df -h"
  register: partition_info

- name: get swap info
  shell: free -m|grep Swap|awk '{print $2}'
  register: swap_info

- import_tasks: home.yml
  when: '"/dev/mapper/centos-home" in partition_info.stdout'

- import_tasks: swap.yml
  when: swap_info.stdout != "0"
