---
- name: set_fact registry_server
  set_fact:
    registry_server: |-
      {%- set registry_server = hostvars[groups.k8s_master.0]['ansible_host'] -%}
      {%- if 'registry_server' in groups and groups.registry_server|length > 0 -%}
        {% set registry_server = hostvars[groups.registry_server.0]['ansible_host'] %}
      {%- endif -%}
      {{ registry_server }}
  run_once: true
  delegate_to: localhost

- name: show registry_server
  debug:
    msg: "{{ registry_server }}"
  run_once: true
  delegate_to: localhost

- name: setup {{ REGISTRY_HOST }} hosts
  blockinfile:
    path: /etc/hosts
    block: "{{ registry_server }} {{ REGISTRY_HOST }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK registry"
    insertafter: EOF
