---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
- name: download official helm package on control node
  get_url:
    url: "https://get.helm.sh/helm-v{{ HELM_VER }}-linux-amd64.tar.gz"
    dest: "/tmp/helm-v{{ HELM_VER }}-linux-amd64.tar.gz"
    checksum: "sha256:https://get.helm.sh/helm-v{{ HELM_VER }}-linux-amd64.tar.gz.sha256sum"
  run_once: true
  # http://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html
  # connection: local
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html
  delegate_to: localhost
  when: helm_url == "official"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
- name: download huaweicloud helm package on control node
  get_url:
    url: "https://mirrors.huaweicloud.com/helm/v{{ HELM_VER }}/helm-v{{ HELM_VER }}-linux-amd64.tar.gz"
    dest: "/tmp/helm-v{{ HELM_VER }}-linux-amd64.tar.gz"
    # checksum: "sha256:https://mirrors.huaweicloud.com/helm/v{{ HELM_VER }}/helm-v{{ HELM_VER }}-linux-amd64.tar.gz.sha256"
  run_once: true
  # http://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html
  # connection: local
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html
  delegate_to: localhost
  when: helm_url == "huaweicloud"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: copy helm package to all k8s_master nodes
  copy:
    src: "/tmp/helm-v{{ HELM_VER }}-linux-amd64.tar.gz"
    dest: "/tmp/helm-v{{ HELM_VER }}-linux-amd64.tar.gz"

- name: unarchive helm package
  unarchive:
    src: "/tmp/helm-v{{ HELM_VER }}-linux-amd64.tar.gz"
    dest: /usr/local
    owner: root

- name: create helm symbolic link
  file:
    src: /usr/local/linux-amd64/helm
    dest: /usr/local/bin/helm
    state: link
