---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
- name: setup official kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgcheck: yes
    enabled: yes
    file: kubernetes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state: present
  notify: yum makecache
  when: K8S_REPO == "official"

# https://developer.aliyun.com/mirror/kubernetes
- name: setup aliyun kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
    gpgcheck: yes
    enabled: yes
    file: kubernetes
    gpgkey: https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
    state: present
  notify: yum makecache
  when: K8S_REPO == "aliyun"

# https://mirrors.tuna.tsinghua.edu.cn/help/kubernetes/
- name: setup tuna kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://mirrors.tuna.tsinghua.edu.cn/kubernetes/yum/repos/kubernetes-el7-$basearch
    gpgcheck: no
    enabled: yes
    file: kubernetes
    state: present
  notify: yum makecache
  when: K8S_REPO == "tuna"

- name: setup ustc kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://mirrors.ustc.edu.cn/kubernetes/yum/repos/kubernetes-el7-$basearch
    gpgcheck: no
    enabled: yes
    file: kubernetes
    state: present
  notify: yum makecache
  when: K8S_REPO == "ustc"

- name: setup huaweicloud kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://repo.huaweicloud.com/kubernetes/yum/repos/kubernetes-el7-$basearch
    gpgcheck: yes
    enabled: yes
    file: kubernetes
    gpgkey: https://repo.huaweicloud.com/kubernetes/yum/doc/yum-key.gpg https://repo.huaweicloud.com/kubernetes/yum/doc/rpm-package-key.gpg
    state: present
  notify: yum makecache
  when: K8S_REPO == "huaweicloud"

- name: setup custom kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: "{{ K8S_REPO }}"
    gpgcheck: no
    enabled: yes
    file: kubernetes
    state: present
  notify: yum makecache
  when: K8S_REPO not in k8s_builtin_options

# http://www.jinbuguo.com/systemd/systemd.slice.html
# http://www.jinbuguo.com/systemd/systemd.resource-control.html
# http://www.jinbuguo.com/systemd/systemd.unit.html
# http://www.jinbuguo.com/systemd/systemd.service.html
# https://www.cnblogs.com/sparkdev/p/8448237.html
# https://www.cnblogs.com/sparkdev/p/9523194.html
# https://developer.aliyun.com/article/810635
- name: copy systemd unit
  copy:
    src: system
    dest: /etc/systemd
  notify: enable kubernetes.slice

- name: force all notified handlers to run at this point
  meta: flush_handlers
