---
- include_tasks: partition.yml
  vars:
    prefix: |-
      {%- set prefix = '' -%}
      {%- if ansible_facts['distribution_major_version'] == '7' -%}
        {% set prefix = 'centos' %}
      {%- elif ansible_facts['distribution_major_version'] == '8' -%}
        {% set prefix = 'rl' %}
      {%- endif -%}
      {{ prefix }}

- block:
    - include_tasks: repo_centos7.yml
      when: ansible_facts["distribution_major_version"] == "7"

    - include_tasks: repo_rocky8.yml
      when: ansible_facts["distribution_major_version"] == "8"

- include_tasks: utilities.yml

- include_tasks: pypi.yml

- include_tasks: ntp.yml
