---
- name: setup official pypi source
  file:
    path: ~/.config/pip
    state: absent
  when: PYPI_SOURCE == "official"

- name: setup aliyun pypi source
  block:
    - name: create pypi config directory
      file:
        path: ~/.config/pip
        state: directory

    - name: setup aliyun pip.conf
      vars:
        pypi_url: https://mirrors.aliyun.com/pypi/simple/
      template:
        src: pip.conf.j2
        dest: ~/.config/pip/pip.conf
      notify: upgrade pip

  when: PYPI_SOURCE == "aliyun"

- name: setup tuna pypi source
  block:
    - name: create pypi config directory
      file:
        path: ~/.config/pip
        state: directory

    - name: setup tuna pip.conf
      vars:
        pypi_url: https://pypi.tuna.tsinghua.edu.cn/simple
      template:
        src: pip.conf.j2
        dest: ~/.config/pip/pip.conf
      notify: upgrade pip

  when: PYPI_SOURCE == "tuna"

- name: setup ustc pypi source
  block:
    - name: create pypi config directory
      file:
        path: ~/.config/pip
        state: directory

    - name: setup ustc pip.conf
      vars:
        pypi_url: https://mirrors.ustc.edu.cn/pypi/web/simple
      template:
        src: pip.conf.j2
        dest: ~/.config/pip/pip.conf
      notify: upgrade pip

  when: PYPI_SOURCE == "ustc"

- name: setup custom pypi source
  block:
    - name: create pypi config directory
      file:
        path: ~/.config/pip
        state: directory

    - name: setup custom pip.conf
      vars:
        pypi_url: "{{ PYPI_SOURCE }}"
      template:
        src: pip.conf.j2
        dest: ~/.config/pip/pip.conf
      notify: upgrade pip

  when: PYPI_SOURCE not in pypi_builtin_options

- name: force all notified handlers to run at this point
  meta: flush_handlers
