---
- name: setup official pypi source
  file:
    path: ~/.config/pip
    state: absent
  when: pypi_source == "official"

- name: setup aliyun pypi source
  block:
    - name: create pypi config directory
      file:
        path: ~/.config/pip
        state: directory

    - name: setup aliyun pip.conf
      vars:
        pypi_url: https://mirrors.aliyun.com/pypi/simple/
      template:
        src: pip.conf.j2
        dest: ~/.config/pip/pip.conf
      notify: upgrade pip

  when: pypi_source == "aliyun"

- name: setup tuna pypi source
  block:
    - name: create pypi config directory
      file:
        path: ~/.config/pip
        state: directory

    - name: setup tuna pip.conf
      vars:
        pypi_url: https://pypi.tuna.tsinghua.edu.cn/simple
      template:
        src: pip.conf.j2
        dest: ~/.config/pip/pip.conf
      notify: upgrade pip

  when: pypi_source == "tuna"

- name: force all notified handlers to run at this point
  meta: flush_handlers
