---
- name: setup CentOS-Base official repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    mirrorlist: "{{ item.mirrorlist }}"
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
    file: CentOS-Base
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    state: present
  with_items:
    - name: base
      description: CentOS-$releasever - Base
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
      enabled: yes
    - name: updates
      description: CentOS-$releasever - Updates
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
      enabled: yes
    - name: extras
      description: CentOS-$releasever - Extras
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
      enabled: yes
    - name: centosplus
      description: CentOS-$releasever - Plus
      mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra
      enabled: no
  notify:
    - yum clean all
    - yum makecache
  when: YUM_SOURCE == "official"

- name: setup CentOS-Base aliyun repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
    file: CentOS-Base
    gpgkey: http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7
    state: present
  with_items:
    - name: base
      description: CentOS-$releasever - Base
      baseurl: http://mirrors.aliyun.com/centos/$releasever/os/$basearch/
      enabled: yes
    - name: updates
      description: CentOS-$releasever - Updates
      baseurl: http://mirrors.aliyun.com/centos/$releasever/updates/$basearch/
      enabled: yes
    - name: extras
      description: CentOS-$releasever - Extras
      baseurl: http://mirrors.aliyun.com/centos/$releasever/extras/$basearch/
      enabled: yes
    - name: centosplus
      description: CentOS-$releasever - Plus
      baseurl: http://mirrors.aliyun.com/centos/$releasever/centosplus/$basearch/
      enabled: no
  notify:
    - yum clean all
    - yum makecache
  when: YUM_SOURCE == "aliyun"

- name: setup CentOS-Base tuna repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
    file: CentOS-Base
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    state: present
  with_items:
    - name: base
      description: CentOS-$releasever - Base
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/
      enabled: yes
    - name: updates
      description: CentOS-$releasever - Updates
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/
      enabled: yes
    - name: extras
      description: CentOS-$releasever - Extras
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/
      enabled: yes
    - name: centosplus
      description: CentOS-$releasever - Plus
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/centosplus/$basearch/
      enabled: no
  notify:
    - yum clean all
    - yum makecache
  when: YUM_SOURCE == "tuna"

- name: setup CentOS-Base ustc repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
    file: CentOS-Base
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    state: present
  with_items:
    - name: base
      description: CentOS-$releasever - Base
      baseurl: https://mirrors.ustc.edu.cn/centos/$releasever/os/$basearch/
      enabled: yes
    - name: updates
      description: CentOS-$releasever - Updates
      baseurl: https://mirrors.ustc.edu.cn/centos/$releasever/updates/$basearch/
      enabled: yes
    - name: extras
      description: CentOS-$releasever - Extras
      baseurl: https://mirrors.ustc.edu.cn/centos/$releasever/extras/$basearch/
      enabled: yes
    - name: centosplus
      description: CentOS-$releasever - Plus
      baseurl: https://mirrors.ustc.edu.cn/centos/$releasever/centosplus/$basearch/
      enabled: no
  notify:
    - yum clean all
    - yum makecache
  when: YUM_SOURCE == "ustc"

- name: setup CentOS-Base custom repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
    file: CentOS-Base
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    state: present
  with_items:
    - name: base
      description: CentOS-$releasever - Base
      baseurl: "{{ YUM_SOURCE }}/$releasever/os/$basearch/"
      enabled: yes
    - name: updates
      description: CentOS-$releasever - Updates
      baseurl: "{{ YUM_SOURCE }}/$releasever/updates/$basearch/"
      enabled: yes
    - name: extras
      description: CentOS-$releasever - Extras
      baseurl: "{{ YUM_SOURCE }}/$releasever/extras/$basearch/"
      enabled: yes
    - name: centosplus
      description: CentOS-$releasever - Plus
      baseurl: "{{ YUM_SOURCE }}/$releasever/centosplus/$basearch/"
      enabled: no
  notify:
    - yum clean all
    - yum makecache
  when: YUM_SOURCE not in yum_builtin_options

- name: install epel-release
  yum:
    name: epel-release
    state: present
  notify: yum makecache

- name: force all notified handlers to run at this point
  meta: flush_handlers
