---
- name: get all partition info
  command: df -h
  register: partition_info

- name: get swap info
  shell: free -m|grep Swap|awk '{print $2}'
  register: swap_info

- name: merge home partition to root partition
  block:
    - name: umount home partition
      command: umount /home
    - name: disable home partition
      shell:
        cmd: sed -i 's/^\/dev\/mapper\/{{ home_partiton }}/#&/' /etc/fstab
        warn: false
    - name: remove lv of home partition
      shell: lvremove /dev/mapper/{{ home_partiton }} -y
    - name: extend lv of root partition
      command: lvextend -l +100%FREE /dev/mapper/{{ root_partiton }}
    - name: xfs_growfs root partition
      command: xfs_growfs /dev/mapper/{{ root_partiton }}
  # https://github.com/ansible/ansible/issues/22397
  when: home_partiton in partition_info.stdout

- name: diable swap partition
  block:
    - name: disable swap partition temporarily
      command: swapoff -a
    - name: disable swap partition permanently
      shell:
        cmd: sed -i 's/^\/dev\/mapper\/{{ swap_partiton }}/#&/' /etc/fstab
        warn: false
  when: swap_info.stdout != "0"
