---
- name: setup official pypi source
  file:
    path: ~/.config/pip
    state: absent
  when: pypi_source == "official"

- name: setup tuna pypi source
  block:
    - name: create pypi config directory
      file:
        path: ~/.config/pip
        state: directory
    - name: setup tuna pip.conf
      copy:
        src: pip.conf
        dest: ~/.config/pip/pip.conf
      notify: upgrade pip
  when: pypi_source == "tuna"

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
