---
yum_builtin_options:
  - "official"
  - "aliyun"
  - "tuna"
  - "ustc"
YUM_SOURCE: aliyun

dnf_builtin_options:
  - "official"
  - "aliyun"
  - "nju"
  - "ustc"
DNF_SOURCE: aliyun

pypi_builtin_options:
  - "official"
  - "aliyun"
  - "tuna"
  - "ustc"
PYPI_SOURCE: aliyun

centos7_utilities:
  - bash-completion # bash命令补全工具
  - bind-utils
  - conntrack-tools # ipvs 模式需要
  - ipset # ipvs 模式需要
  - ipvsadm # ipvs 模式需要
  - libseccomp # 安装 containerd 需要
  - net-tools
  - nfs-utils # 启用 nfs-provisioner 扩展需要
  - openssl
  - openssh
  - python36
  - socat # 用于 port forwarding
  - yum-utils

rocky8_utilities:
  - bind-utils
  - conntrack-tools # ipvs 模式需要
  - ipset # ipvs 模式需要
  - ipvsadm # ipvs 模式需要
  - libseccomp # 安装 containerd 需要
  - net-tools
  - nfs-utils # 启用 nfs-provisioner 扩展需要
  - openssl
  - openssh
  - python36
  - socat # 用于 port forwarding
