---
repo_mirrors: aliyun
pypi_source: aliyun

centos7_utilities:
  - bash-completion
  - yum-utils
  - openssh
  - python36
  # - java-11-openjdk
  - ipvsadm
  - bind-utils
  - bridge-utils

rocky8_utilities:
  - openssh
  - python36
  # - java-11-openjdk
  - ipvsadm
  - bind-utils
  - bridge-utils
