---
- name: check k8s mode
  block:
    - name: check number of k8s_master node
      assert:
        that:
          - groups.k8s_master|length in [1, 3]
        fail_msg: "The number of k8s_master node must be 1 or 3"

    - name: check kubernetes high availability mode
      assert:
        that:
          - HA_ENABLE == "yes"
        fail_msg: 'HA_ENABLE="yes" must be set for high availability mode'
      # https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
      when: groups.k8s_master|length == 3

    - name: check kubernetes non high availability mode
      assert:
        that:
          - HA_ENABLE == "no"
        fail_msg: 'HA_ENABLE="no" must be set for non high availability mode'
      # https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
      when: groups.k8s_master|length == 1
