---
# https://www.middlewareinventory.com/blog/ansible-inventory_hostname-ansible_hostname-variables
- name: setup node hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: setup node hosts
  vars:
    hosts: |-
      {%- set hosts = [] -%}
      {%- for host in groups['all'] -%}
        {{ hosts.append({'host': host, 'ip': hostvars[host]['ansible_host']}) }}
      {%- endfor -%}
      {{- hosts -}}
  lineinfile:
    path: /etc/hosts
    regexp: "{{ item.host }}$"
    line: "{{ item.ip }} {{ item.host }}"
    insertbefore: BOF
  with_items: "{{ hosts }}"
