---
- hosts: ntp_server
  any_errors_fatal: true
  roles:
    - role: ntp
  vars:
    ntp_servers: []
    ntp_pools:
      - 2.centos.pool.ntp.org iburst

- hosts: k8s
  any_errors_fatal: true
  tasks:
    - name: setup {{ ntp_service }} hosts
      vars:
        ips: |-
          {%- set ips = [] -%}
            {%- for host in groups['ntp_server'] -%}
              {{ ips.append(hostvars[host]['ansible_host']) }}
            {%- endfor -%}
          {{- ips|unique -}}
      lineinfile:
        path: /etc/hosts
        regexp: "{{ ntp_service }}$"
        line: "{{ item }} {{ ntp_service }}"
        insertafter: EOF
      with_items: "{{ ips }}"

- hosts: k8s:!ntp_server
  any_errors_fatal: true
  roles:
    - role: ntp
  vars:
    ntp_servers:
      - ntp.service iburst
    ntp_pools: []
