---
- name: install kubernetes packages
  yum:
    name:
      - kubeadm-{{ K8S_VER }}
      - kubelet-{{ K8S_VER }}
      - kubectl-{{ K8S_VER }}
    state: present
  notify: enable kubelet

- name: create user kube directory
  file:
    path: ~/.kube
    state: directory

# https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability/
# https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#options-for-software-load-balancing
- include_tasks: haproxy.yml
  when: HA_ENABLE == "yes"

- include_tasks: keepalived.yml
  vars:
    keepalived_state: MASTER
    keepalived_priority: 101
  when: HA_ENABLE == "yes" and inventory_hostname == groups.k8s_master.0

- include_tasks: keepalived.yml
  vars:
    keepalived_state: BACKUP
    keepalived_priority: 100
  when: HA_ENABLE == "yes" and inventory_hostname != groups.k8s_master.0
