---
- name: generate k8s join command
  shell: kubeadm token create --ttl 5m --print-join-command --certificate-key "$(kubeadm init phase upload-certs --upload-certs --skip-headers --skip-log-headers | tail -n 1)"
  register: k8s_master_join_result
  run_once: true
  delegate_to: "{{ groups.k8s_master.0 }}"

- set_fact:
    k8s_master_join_cmd: "{{ k8s_master_join_result.stdout }}"
  run_once: true

- name: join k8s master
  shell:
    cmd: "{{ k8s_master_join_cmd }} --ignore-preflight-errors=DirAvailable--var-lib-etcd"
    creates: /etc/kubernetes/admin.conf

- name: create user kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    mode: 0600
    remote_src: yes
