---
- name: stop and disable firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: false

# https://www.middlewareinventory.com/blog/ansible-inventory_hostname-ansible_hostname-variables
- name: setup node hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: setup node hosts
  vars:
    hosts: |-
      {%- set hosts = [] -%}
      {%- for host in groups['k8s'] -%}
        {{ hosts.append({'host': host, 'ip': hostvars[host]['ansible_host']}) }}
      {%- endfor -%}
      {{- hosts -}}
  lineinfile:
    path: /etc/hosts
    regexp: "{{ item.host }}$"
    line: "{{ item.ip }} {{ item.host }}"
    insertbefore: BOF
  with_items: "{{ hosts }}"

- name: disable selinux
  selinux:
    state: disabled

- name: install utilities
  block:
    - name: install centos7 utilities
      yum:
        name: "{{ centos7_utilities }}"
        state: present
      when:
        - ansible_facts["distribution"] == "CentOS"
        - ansible_facts["distribution_major_version"] == "7"
    - name: install rocky8 utilities
      yum:
        name: "{{ rocky8_utilities }}"
        state: present
      when:
        - ansible_facts["distribution"] == "Rocky"
        - ansible_facts["distribution_major_version"] == "8"

- name: setup kernel parameters
  copy:
    src: 00-sysctl.conf
    dest: /etc/sysctl.d
  notify: reload sysctl

- name: setup rsyslog
  yum:
    name: rsyslog
    state: latest
  notify: restart rsyslog

- name: setup logrotate
  block:
    - name: stat logrotate
      stat:
        path: /etc/cron.daily/logrotate
      register: logrotate_stat
    - name: change logrotate time to hourly
      command: mv -f /etc/cron.daily/logrotate /etc/cron.hourly/
      when: logrotate_stat.stat.exists

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
