---
- name: yum makecache
  command:
    cmd: yum makecache
    warn: false

- name: enable kubernetes.slice
  systemd:
    state: started
    enabled: yes
    name: kubernetes.slice

- name: restart and enable containerd
  systemd:
    daemon_reload: yes
    enabled: yes
    name: containerd
    state: restarted
  when: CONTAINER_RUNTIME == "containerd"

- name: restart and enable docker
  systemd:
    daemon_reload: yes
    enabled: yes
    name: docker
    state: restarted
  when: CONTAINER_RUNTIME == "docker"
