---
- name: yum makecache
  command:
    cmd: yum makecache
    warn: false

- name: restart and enable docker
  systemd:
    daemon_reload: yes
    enabled: yes
    name: docker
    state: restarted
