---
- name: setup CentOS-Base tuna repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    enabled: "{{ item.enabled }}"
    file: CentOS-Base
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    state: present
  with_items:
    - name: base
      description: CentOS-$releasever - Base
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/
      enabled: yes
    - name: updates
      description: CentOS-$releasever - Updates
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/
      enabled: yes
    - name: extras
      description: CentOS-$releasever - Extras
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/
      enabled: yes
    - name: centosplus
      description: CentOS-$releasever - Plus
      baseurl: https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/centosplus/$basearch/
      enabled: no
  notify: yum makecache
