---
- name: generate k8s worker join common
  shell: kubeadm token create --ttl 5m --print-join-command
  register: k8s_worker_join_result
  run_once: true
  delegate_to: "{{ groups.k8s_master.0 }}"

- set_fact:
    k8s_worker_join_cmd: "{{ k8s_worker_join_result.stdout }}"
  run_once: true

- name: join k8s worker
  shell:
    cmd: "{{ k8s_worker_join_cmd }}"
    creates: /etc/kubernetes/kubelet.conf
