---
- name: generate k8s worker join command
  shell: kubeadm token create --ttl 5m --print-join-command
  register: k8s_worker_join_result
  run_once: true
  delegate_to: "{{ groups.k8s_master.0 }}"

- set_fact:
    k8s_worker_join_cmd: "{{ k8s_worker_join_result.stdout|trim }}"
  run_once: true

- name: show k8s_worker_join_cmd
  debug:
    msg: "{{ k8s_worker_join_cmd }}"
  run_once: true

- name: join k8s worker
  shell:
    cmd: "{{ k8s_worker_join_cmd }}"
    creates: /etc/kubernetes/kubelet.conf

- name: set "worker" label for the node
  command: kubectl label --overwrite nodes {{ inventory_hostname }} node-role.kubernetes.io/worker=
  delegate_to: "{{ groups.k8s_master.0 }}"
