---
- block:
    - name: install the harbor server's CA cert on k8s nodes
      copy:
        src: /tmp/ca.crt
        dest: /etc/pki/ca-trust/source/anchors/harbor-ca.crt
      notify:
        - update trusted ca-certificates
        - restart containerd

  when: CONTAINER_RUNTIME == "containerd"

- block:
    - name: create cert dir for the docker daemon
      file:
        path: /etc/docker/certs.d/{{ HARBOR_HOST }}:{{ HARBOR_HTTPS_PORT }}
        state: directory

    - name: install the harbor server's CA cert for docker
      copy:
        src: /tmp/ca.crt
        dest: /etc/docker/certs.d/{{ HARBOR_HOST }}:{{ HARBOR_HTTPS_PORT }}/ca.crt
      notify: restart docker

  when: CONTAINER_RUNTIME == "docker"

- name: force all notified handlers to run at this point
  meta: flush_handlers
