---
- block:
    - block:
        - name: check if harbor is enabled
          command: ls /etc/docker/certs.d/{{ HARBOR_HOST }}:{{ HARBOR_PORT }}
          register: result
        - set_fact:
            harbor_enabled: '{{ "ca.crt" in result.stdout }}'

    - block:
        - name: create cert dir for the docker daemon
          file:
            path: /etc/docker/certs.d/{{ HARBOR_HOST }}:{{ HARBOR_PORT }}
            state: directory
        - name: install the harbor server's CA cert for docker
          copy:
            src: /tmp/ca.crt
            dest: /etc/docker/certs.d/{{ HARBOR_HOST }}:{{ HARBOR_PORT }}/ca.crt
        - name: restart docker
          service:
            name: docker
            state: restarted
      when: not harbor_enabled

  when: CONTAINER_RUNTIME == "docker"

- block:
    - block:
        - name: check if harbor is enabled
          command: ls /etc/pki/ca-trust/source/anchors/
          register: result
        - set_fact:
            harbor_enabled: '{{ "harbor-ca.crt" in result.stdout }}'

    - block:
        - name: install the harbor server's CA cert on k8s nodes
          copy:
            src: /tmp/ca.crt
            dest: /etc/pki/ca-trust/source/anchors/harbor-ca.crt
        - name: update the trusted ca-certificates
          command: update-ca-trust
        - name: restart containerd
          service:
            name: containerd
            state: restarted
      when: not harbor_enabled

  when: CONTAINER_RUNTIME == "containerd"
