---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
- name: download helm package on control node
  get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "~/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    checksum: "sha256:https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz.sha256sum"
  # http://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html
  # connection: local
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html
  delegate_to: localhost
  tags:
    - k8s_helm

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: copy helm package to all k8s_master nodes
  copy:
    src: "~/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "~/helm-v{{ helm_version }}-linux-amd64.tar.gz"
  tags:
    - k8s_helm

- name: unarchive helm package
  unarchive:
    src: "~/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/share
    owner: root
  tags:
    - k8s_helm

- name: create helm symbolic link
  file:
    src: /usr/share/linux-amd64/helm
    dest: /usr/sbin/helm
    state: link
  tags:
    - k8s_helm
