---
- name: get all created pod info
  command: "kubectl get pod --all-namespaces"
  register: pod_info
  run_once: true
  delegate_to: "{{ groups.k8s_master.0 }}"

- import_tasks: dashboard.yml
  when: '"kubernetes-dashboard" not in pod_info.stdout and dashboard_enbale|bool'
