---
- name: setup Rocky-AppStream official repository
  yum_repository:
    name: appstream
    description: Rocky Linux $releasever - AppStream
    mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=AppStream-$releasever
    gpgcheck: yes
    enabled: yes
    file: Rocky-AppStream
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    state: present
  notify: dnf makecache

- name: setup Rocky-BaseOS official repository
  yum_repository:
    name: baseos
    description: Rocky Linux $releasever - BaseOS
    mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=BaseOS-$releasever
    gpgcheck: yes
    enabled: yes
    file: Rocky-BaseOS
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    state: present
  notify: dnf makecache

- name: setup Rocky-Extras official repository
  yum_repository:
    name: extras
    description: Rocky Linux $releasever - Extras
    mirrorlist: https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=extras-$releasever
    gpgcheck: yes
    enabled: yes
    file: Rocky-Extras
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    state: present
  notify: dnf makecache
