---
- name: setup docker-ce official repository
  shell:
    # https://github.com/ansible/ansible/issues/46963
    cmd: dnf config-manager --add-repo {{ docker_official_repo }}
  notify: dnf makecache
  when: docker_repo == "official"
  tags:
    - official-docker-ce

- name: setup docker-ce aliyun repository
  shell:
    cmd: dnf config-manager --add-repo {{ docker_aliyun_repo }}
  notify: dnf makecache
  when: docker_repo == "aliyun"
  tags:
    - aliyun-docker-ce

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: create a ext4 filesystem on {{ docker_imagefs_dev }} and check disk blocks
  filesystem:
    fstype: ext4
    dev: "{{ docker_imagefs_dev }}"
    opts: "{{ docker_imagefs_opts }}"
  when: (docker_imagefs_dev is defined) and (docker_imagefs_dev|length > 0)
  tags:
    - docker-ce
  register: docker_filesystem_result

- when: docker_filesystem_result.changed
  set_fact:
    docker_imagefs_mount_src: LABEL={{ docker_imagefs_label }}

- name: mount {{ docker_imagefs_mount_src }} on /var/lib/docker
  mount:
    path: /var/lib/docker
    src: "{{ docker_imagefs_mount_src }}"
    fstype: ext4
    state: mounted
  when: (docker_imagefs_mount_src is defined) and (docker_imagefs_mount_src|length > 0)
  tags:
    - docker-ce

# https://github.com/ansible/ansible/issues/71808
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html#parameter-name
- name: install docker-ce
  dnf:
    name: docker-ce-{{ docker_version }}
    state: present
  # https://stackoverflow.com/questions/41194021/how-can-i-show-progress-for-a-long-running-ansible-task
  async: 30000
  poll: 0
  register: dnf_sleeper
  notify: restart and enable docker
  tags:
    - docker-ce

- name: whether docker has completed the installation
  async_status:
    jid: "{{ dnf_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 20
  tags:
    - docker-ce

- name: create docker config directory
  file:
    path: /etc/docker
    state: directory
  tags:
    - docker-ce

- name: create docker config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  notify: restart and enable docker
  tags:
    - docker-ce

- meta: flush_handlers
