---
- name: setup Rocky-AppStream official repository
  yum_repository:
    name: appstream
    description: Rocky Linux $releasever - AppStream
    baseurl: https://mirrors.nju.edu.cn/rocky/$releasever/AppStream/$basearch/os/
    gpgcheck: yes
    enabled: yes
    file: Rocky-AppStream
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    state: present
  notify: dnf makecache

- name: setup Rocky-BaseOS official repository
  yum_repository:
    name: baseos
    description: Rocky Linux $releasever - BaseOS
    baseurl: https://mirrors.nju.edu.cn/rocky/$releasever/BaseOS/$basearch/os/
    gpgcheck: yes
    enabled: yes
    file: Rocky-BaseOS
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    state: present
  notify: dnf makecache

- name: setup Rocky-Extras official repository
  yum_repository:
    name: extras
    description: Rocky Linux $releasever - Extras
    baseurl: https://mirrors.nju.edu.cn/rocky/$releasever/extras/$basearch/os/
    gpgcheck: yes
    enabled: yes
    file: Rocky-Extras
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    state: present
  notify: dnf makecache
