---
- name: stop and disable firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: disable selinux
  selinux:
    state: disabled

# https://www.middlewareinventory.com/blog/ansible-inventory_hostname-ansible_hostname-variables
- name: setup node hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: load kernel module
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack
  ignore_errors: true

- name: try to load nf_conntrack_ipv4
  shell: modprobe nf_conntrack_ipv4 || echo "NotFound"
  register: nf_conntrack_ipv4

- name: add kernel module startup loading config
  template:
    src: 10-k8s-modules.conf.j2
    dest: /etc/modules-load.d/10-k8s-modules.conf
  notify: enable systemd-modules-load

- name: setup kernel parameters
  copy:
    src: 90-k8s-sysctl.conf
    dest: /etc/sysctl.d
  notify: reload sysctl

- name: force all notified handlers to run at this point
  meta: flush_handlers
