---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: prepare/check

- hosts: k8s
  any_errors_fatal: true
  roles:
    - role: prepare/base
    - role: prepare/hosts
    - role: prepare/centos
      when: ansible_facts["distribution"] in ["CentOS", "Rocky"]
    - role: prepare/ntp
    - role: prepare/reboot
