---
- hosts: k8s
  any_errors_fatal: true
  roles:
    - role: runtime/docker
      when: CONTAINER_RUNTIME == "docker"

# https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
- hosts: k8s:local_registry_server
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: runtime/hosts

# use an external existing local registry server
- hosts: local_registry_server
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: runtime/registry
      when: ('local_registry_server' in groups)
        and (groups.local_registry_server|length > 0)

# make k8s_master[0] as a local registry server
- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: runtime/registry
      when: ('local_registry_server' not in groups)
        or (groups.local_registry_server|length == 0)
