---
- hosts: k8s_master
  any_errors_fatal: true
  roles:
    - role: k8s_common
      tags: k8s_common
    - role: k8s_master/preflight
      tags: k8s_master

- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_master/init
      tags: k8s_master

- hosts: k8s_master[1:]
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_master/join
      tags: k8s_master
