---
- hosts: k8s_worker
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_common
      tags: k8s_common
    - role: k8s_worker/preflight
      tags: k8s_worker
    - role: k8s_worker/join
      tags: k8s_worker
