---
- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_network/calico
      when: CLUSTER_NETWORK == "calico"
    - role: k8s_network/flannel
      when: CLUSTER_NETWORK == "flannel"
