---
- hosts: k8s_master
  any_errors_fatal: true
  roles:
    - role: k8s_addon
      tags: k8s_addon
      vars:
        addon: helm

- hosts: k8s_master[0]
  any_errors_fatal: true
  roles:
    - role: k8s_addon
      tags: k8s_addon
      vars:
        addon: dashboard
