---
# use an external existing registry server
- hosts: registry_server
  any_errors_fatal: true
  gather_facts: false
  roles:
    # 提前拉取扩展需要的镜像并推送到本地仓库
    - role: runtime/registry
      when: ('registry_server' in groups)
        and (groups.registry_server|length > 0)

# make k8s_master[0] as a registry server
- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  roles:
    # 提前拉取扩展需要的镜像并推送到本地仓库
    - role: runtime/registry
      when: ('registry_server' not in groups)
        or (groups.registry_server|length == 0)

- hosts: k8s_master:ansible_client
  any_errors_fatal: true
  roles:
    - role: prepare/nfs
      when: nfs_server is defined and nfs_server == "yes"

- hosts: k8s_master
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_addon/helm
      when: HELM_ENABLE == "yes"

- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_addon/nodelocaldns
      when: NODELOCALDNS_ENABLE == "yes"
    - role: k8s_addon/metrics_server
      when: METRICES_SERVER_ENABLE == "yes"
    - role: k8s_addon/nfs_provisioner
      when: NFS_PROVISIONER_ENABLE == "yes"
    - role: k8s_addon/prometheus
      when: PROMETHEUS_ENABLE == "yes"
    - role: k8s_addon/dashboard
      when: DASHBOARD_ENABLE == "yes"
