---
- hosts: k8s_master
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_addon/helm
      tags: k8s_addon
      when: HELM_ENABLE == "yes"

- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: k8s_addon/metrics_server
      tags: k8s_addon
      when: METRICES_SERVER_ENABLE == "yes"
    - role: k8s_addon/dashboard
      tags: k8s_addon
      when: DASHBOARD_ENABLE == "yes"
