---
- hosts: k8s
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: check nodes
      assert:
        that:
          - nodes is defined
          - nodes|length > 0
        fail_msg: 'The extra argument "nodes" can not be empty'
      run_once: true
      delegate_to: localhost

    - name: get all worker nodes in the cluster
      shell: >-
        set -o pipefail &&
        kubectl get node
        -l 'node-role.kubernetes.io/worker'
        --no-headers |
        awk '{print $1}'
      register: result
      run_once: true
      delegate_to: "{{ groups.k8s_master.0 }}"

    - set_fact:
        workers: "{{ result.stdout_lines }}"
      run_once: true
      delegate_to: "{{ groups.k8s_master.0 }}"

- import_playbook: 00.sshkey.yml

- hosts: k8s
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: prepare/hosts

- hosts: "{{ nodes }}"
  any_errors_fatal: true
  tasks:
    - block:
        - include_role:
            name: prepare/base
        - include_role:
            name: prepare/centos
          when: ansible_facts["distribution"] in ["CentOS", "Rocky"]
        - include_role:
            name: prepare/ntp
        - include_role:
            name: prepare/reboot
        - include_role:
            name: runtime/common
        - include_role:
            name: runtime/containerd
          when: CONTAINER_RUNTIME == "containerd"
        - include_role:
            name: runtime/docker
          when: CONTAINER_RUNTIME == "docker"
        - include_role:
            name: runtime/hosts
        - include_role:
            name: k8s_common
        - include_role:
            name: k8s_worker/preflight
        - include_role:
            name: k8s_worker/join
      when: inventory_hostname not in workers

- import_playbook: 81.harbor.yml
