---
- hosts: k8s
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: check nodes
      assert:
        that:
          - nodes is defined
          - nodes|length > 0
        fail_msg: 'The extra argument "nodes" can not be empty'
      run_once: true
      delegate_to: localhost
    - name: get all worker nodes in the cluster
      shell: >-
        set -o pipefail &&
        kubectl get node
        -l 'node-role.kubernetes.io/worker'
        --no-headers |
        awk '{print $1}'
      register: result
      run_once: true
      delegate_to: "{{ groups.k8s_master.0 }}"
    - set_fact:
        workers: "{{ result.stdout_lines }}"
      run_once: true
      delegate_to: "{{ groups.k8s_master.0 }}"
  tags: remove_worker

- hosts: k8s_master[0]
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - include_role:
        name: k8s_worker/remove
      vars:
        worker: "{{ item }}"
      when: item in workers
      with_items: "{{ nodes|split(':')|unique }}"
  tags: remove_worker

- hosts: "{{ nodes }}"
  any_errors_fatal: true
  tasks:
    - block:
        - name: populate service facts
          service_facts:
        - include_tasks: roles/reset/tasks/kubelet.yml
      when: inventory_hostname in workers
  tags: remove_worker
